# W07 Team Activity.

# Name: Lucas Neves Rocha.
# Course: Programming building blocks.
# Instructor: Travis Christiansen.

# Task: Create a "guess my number" game.

# Importing "os" literally to made it cleaner.
# Random library to make it work.

from os import system as clean
import random

# Stating the main condition to determine if the whole game will run as a loop.
play_again = "yes"

while play_again == "yes":

# Guess and attempt fields are malleable. 
    magic_number = random.randint(1, 100)
    guess = -1
    attempt = 0

# Every time the guessed number is different than the random number generated by the system, it enters in a loop.
# Also, it adds attempts.
    while guess != magic_number:
        attempt = attempt + 1
        guess = int(input("What is your guess? "))
        if guess < magic_number:
            clean("cls")
            attempt + 1
            print("Higher. ")
        elif guess > magic_number:
            clean("cls")
            attempt + 1
            print("Lower. ")

            # When the user types the correct number, it shows how many attempts were made.
        elif guess == magic_number:
            clean("cls")
            print("That's correct. ")
            print(f"You tried {attempt} times. ")
            break
        # Anything else will end the program.
        else:
            print("Wrong input. ")
            break
    play_again = input("Do you want to play again? [yes/no] ")
print("Thank you for playing. ")